[workspace]
members = [
    "zircon-object",
    "zircon-syscall",
    "zircon-loader",
    "linux-object",
    "linux-syscall",
    "linux-loader",
    "kernel-hal-unix",
    "kernel-hal-sel4",
    "kernel-hal",
]

exclude = [
    "zircon-user",
	"zCore",
	"rboot",
    "zcboot-sel4",
]
