[workspace]
members = [
    "drivers",
    "kernel-hal",
    "zircon-object",
    "zircon-syscall",
    "linux-object",
    "linux-syscall",
    "loader",
    "zCore",
]

exclude = [
    "zircon-user",
    "rboot",
]

[profile.release]
lto = true