[workspace]
members = [
    "zircon-object",
    "zircon-syscall",
    "zircon-loader",
    "linux-object",
    "linux-syscall",
    "linux-loader",
    "kernel-hal-unix",
    "kernel-hal-bare",
    "kernel-hal",
]

exclude = [
	"zCore",
	"rboot",
]
