[package]
name = "zcore"
version = "0.1.0"
authors = ["PanQL <panqinglin00@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
spin = "0.5"
buddy_system_allocator = "0.3.8"
rlibc = "1.0"
rboot = { path = "../rboot", default-features = false }
kernel-hal-bare = { path = "../kernel-hal-bare" }
lazy_static = { version = "1.4", features = ["spin_no_std" ] }
bitmap-allocator = { git = "https://github.com/rcore-os/bitmap-allocator" }
trapframe = "0.1.3"
executor = { git = "https://github.com/PanQL/executor.git", rev="2664dd1" }
zircon-loader = { path = "../zircon-loader", default-features = false }

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.9"
uart_16550 = "0.2"
