[package]
name = "zcore"
version = "0.1.0"
authors = ["PanQL <panqinglin00@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
graphic = []
zircon = ["zircon-loader"]
linux = ["linux-loader", "linux-object", "rcore-fs-sfs"]
# for qemu machine
board_malta = []
link_user = []
hypervisor = ["rvm", "zircon", "zircon-object/hypervisor", "zircon-syscall/hypervisor"]

[profile.release]
lto = true

[dependencies]
log = "0.4"
spin = "0.5"
buddy_system_allocator = "0.4.0"
rlibc = "1.0"
# rlibc-opt = { git = "https://github.com/rcore-os/rlibc-opt.git", rev = "0ab1d1e" }
rboot = { path = "../rboot", default-features = false }
kernel-hal = { path = "../kernel-hal" }
kernel-hal-bare = { path = "../kernel-hal-bare" }
lazy_static = { version = "1.4", features = ["spin_no_std" ] }
bitmap-allocator = { git = "https://github.com/rcore-os/bitmap-allocator", rev = "03bd9909" }
trapframe = { git = "https://github.com/rcore-os/trapframe-rs", rev = "fed9668" }
executor = { git = "https://github.com/rcore-os/executor.git", rev = "a2d02ee9" }
zircon-object = { path = "../zircon-object" }
zircon-loader = { path = "../zircon-loader", default-features = false, optional = true }
linux-loader = { path = "../linux-loader", default-features = false, optional = true }
linux-object = { path = "../linux-object", default-features = false, optional = true }
rcore-fs = { git = "https://github.com/rcore-os/rcore-fs", rev = "517af47" }
rcore-fs-sfs = { git = "https://github.com/rcore-os/rcore-fs", rev = "e17b27b", optional = true }
device_tree = { git = "https://github.com/rcore-os/device_tree-rs", rev = "eee2c23" }
zircon-syscall = { path = "../zircon-syscall", optional = true }
rvm = { git = "https://github.com/rcore-os/RVM", rev = "4b64355", optional = true }

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.11"

[target.'cfg(target_arch = "mips")'.dependencies]
mips = { git = "https://github.com/Harry-Chen/rust-mips", rev = "3b828a2" }