[package]
name = "zircon-loader"
version = "0.1.0"
authors = ["Runji Wang <wangrunji0408@163.com>"]
edition = "2018"
description = "Zircon user program (userboot) loader"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
spin = "0.5"
xmas-elf = "0.7"
core = { package = "core-futures-tls", version = "0.1.0" }
lazy_static = { version = "1.4", features = ["spin_no_std" ] }
zircon-object = { path = "../zircon-object" }
zircon-syscall = { path = "../zircon-syscall" }
kernel-hal = { path = "../kernel-hal" }
env_logger = { version = "0.7", optional = true }
structopt = { version = "0.3", default-features = false, optional = true }
kernel-hal-unix = { path = "../kernel-hal-unix", optional = true }
async-std = { version = "1.5", features = ["attributes"], optional = true }

[features]
default = ["std"]
std = ["env_logger", "structopt", "async-std", "kernel-hal-unix"]
