[alias]
xtask = "run --package xtask --release --"
git-proxy = "xtask git-proxy"
setup = "xtask setup"
update-all = "xtask update-all"

check-style = "xtask check-style"

rootfs = "xtask rootfs"
opencv = "xtask opencv"
ffmpeg = "xtask ffmpeg"
libc-test = "xtask libc-test"
other-test = "xtask other-test"
image = "xtask image"

linux-libos = "xtask linux-libos"

asm = "xtask asm"
qemu = "xtask qemu"
gdb = "xtask gdb"
